# Generated by Django 5.0.1 on 2024-01-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='img2',
            field=models.FileField(upload_to='pics'),
        ),
    ]
